import type { IntegrationContext } from '../../src/types'
import { beforeEach, describe, expect, it } from 'vitest'
import { createCtx } from '../../src/ctx'

describe('codegen', () => {
	let ctx: IntegrationContext

	const baseOptions = {
		cwd: '/mock/project',
		currentPackageName: '@pikacss/integration',
		scan: { include: ['**/*.ts'], exclude: ['node_modules/**'] },
		configOrPath: null,
		fnName: 'pika',
		transformedFormat: 'string' as const,
		tsCodegen: false as const,
		cssCodegen: 'pika.gen.css',
		autoCreateConfig: false,
	}

	beforeEach(async () => {
		ctx = createCtx(baseOptions)
		await ctx.setup()
	})

	it('should generate CSS from usages', async () => {
		await ctx.transform('const s = pika({ color: "red" })', 'test.ts')

		const css = await ctx.getCssCodegenContent()
		expect(css)
			.toContain('color:')
		expect(css)
			.toContain('red')
	})

	it('should generate CSS with multiple styles', async () => {
		await ctx.transform('const s = pika({ color: "red", display: "flex" })', 'test.ts')

		const css = await ctx.getCssCodegenContent()
		expect(css)
			.toContain('color:')
		expect(css)
			.toContain('red')
		expect(css)
			.toContain('display:')
		expect(css)
			.toContain('flex')
	})

	it('should deduplicate atomic styles across files', async () => {
		await ctx.transform('const s1 = pika({ color: "red" })', 'a.ts')
		await ctx.transform('const s2 = pika({ color: "red" })', 'b.ts')

		const css = await ctx.getCssCodegenContent()
		if (!css)
			return
		// Should only have one class with color: red
		const matches = css.match(/\.a\s*\{[^}]*color:\s*red/g)
		expect(matches)
			.toBeTruthy()
		expect(matches!.length)
			.toBe(1)
	})

	it('should generate CSS for multiple files with different styles', async () => {
		await ctx.transform('const s1 = pika({ color: "red" })', 'a.ts')
		await ctx.transform('const s2 = pika({ color: "blue" })', 'b.ts')
		await ctx.transform('const s3 = pika({ color: "green" })', 'c.ts')

		const css = await ctx.getCssCodegenContent()
		expect(css)
			.toContain('red')
		expect(css)
			.toContain('blue')
		expect(css)
			.toContain('green')
	})

	it('should generate empty CSS with no usages', async () => {
		const css = await ctx.getCssCodegenContent()

		expect(css)
			.toBeDefined()
		if (!css)
			return
		expect(css)
			.toContain('Auto-generated by @pikacss/integration')
		// Should have preflights but no atomic styles
		expect(css.length)
			.toBeGreaterThan(0)
	})

	it('should include preflights in generated CSS', async () => {
		await ctx.transform('const s = pika({ color: "red" })', 'test.ts')

		const css = await ctx.getCssCodegenContent()
		// CSS should start with comment header and preflights
		expect(css)
			.toContain('Auto-generated')
	})

	it('should generate CSS with nested styles', async () => {
		await ctx.transform('const s = pika({ div: { color: "red" } })', 'test.ts')

		const css = await ctx.getCssCodegenContent()
		expect(css)
			.toContain('div')
		expect(css)
			.toContain('color:')
		expect(css)
			.toContain('red')
	})

	it('should generate CSS with media queries', async () => {
		await ctx.transform('const s = pika({ "@media (min-width: 768px)": { color: "red" } })', 'test.ts')

		const css = await ctx.getCssCodegenContent()
		expect(css)
			.toContain('@media')
		expect(css)
			.toContain('min-width: 768px')
		expect(css)
			.toContain('color:')
		expect(css)
			.toContain('red')
	})

	it('should handle TypeScript codegen when enabled', async () => {
		const ctxWithTs = createCtx({
			...baseOptions,
			tsCodegen: 'pika.gen.ts',
		})
		await ctxWithTs.setup()
		await ctxWithTs.transform('const s = pika({ color: "red" })', 'test.ts')

		const tsCode = await ctxWithTs.getTsCodegenContent()
		expect(tsCode)
			.toBeDefined()
		expect(tsCode)
			.toBeTruthy()
	})

	it('should return null for TypeScript codegen when disabled', async () => {
		await ctx.transform('const s = pika({ color: "red" })', 'test.ts')

		const tsCode = await ctx.getTsCodegenContent()
		expect(tsCode)
			.toBeNull()
	})
})
