import type { IntegrationContext } from '../../src/types'
import { beforeEach, describe, expect, it } from 'vitest'
import { createCtx } from '../../src/ctx'

describe('integration Pipeline', () => {
	const baseOptions = {
		cwd: '/mock/project',
		currentPackageName: '@pikacss/integration',
		scan: {
			include: ['**/*.ts'],
			exclude: ['node_modules/**'],
		},
		configOrPath: null,
		fnName: 'pika',
		transformedFormat: 'string' as const,
		tsCodegen: false as const,
		cssCodegen: 'pika.gen.css',
		autoCreateConfig: false,
	}

	let ctx: IntegrationContext

	beforeEach(async () => {
		ctx = createCtx(baseOptions)
		await ctx.setup()
	})

	it('should execute complete transformation pipeline', async () => {
		const sourceCode = `const styles = pika({ color: 'red', display: 'flex' })`
		const result = await ctx.transform(sourceCode, 'Button.tsx')

		// Verify code transformation
		expect(result)
			.toBeDefined()
		expect(result!.code)
			.toMatch(/['"]a b['"]/)

		// Verify usage tracking
		expect(ctx.usages.has('Button.tsx'))
			.toBe(true)
		expect(ctx.usages.get('Button.tsx'))
			.toHaveLength(1)

		// Verify CSS generation
		const css = await ctx.getCssCodegenContent()
		expect(css)
			.toContain('color: red')
		expect(css)
			.toContain('display: flex')
	})

	it('should communicate with Core engine correctly', async () => {
		// Verify engine is initialized
		expect(ctx.resolvedConfig)
			.toBeDefined()

		await ctx.transform('const s = pika({ color: "blue" })', 'test.ts')

		const css = await ctx.getCssCodegenContent()
		// Core engine generates atomic classes
		expect(css)
			.toMatch(/\.\w+\s*\{\s*color:\s*blue;/)
	})

	it('should support array format transformation', async () => {
		const arrayCtx = createCtx({ ...baseOptions, transformedFormat: 'array' })
		await arrayCtx.setup()

		const code = `const styles = pika({ color: 'red' })`
		const result = await arrayCtx.transform(code, 'test.ts')

		expect(result)
			.toBeDefined()
		expect(result!.code)
			.toMatch(/\[['"]a['"]\]/)
	})

	it('should support inline format transformation', async () => {
		const inlineCtx = createCtx({ ...baseOptions, transformedFormat: 'inline' })
		await inlineCtx.setup()

		const code = `const styles = pika({ color: 'red' })`
		const result = await inlineCtx.transform(code, 'test.ts')

		// Inline format returns raw class names without quotes
		expect(result)
			.toBeDefined()
		expect(result!.code)
			.toMatch(/const styles = a/)
	})

	it('should handle multiple style properties in single call', async () => {
		const code = `const styles = pika({ 
			color: 'red', 
			display: 'flex', 
			fontSize: '16px',
			padding: '10px'
		})`
		const result = await ctx.transform(code, 'Component.tsx')

		expect(result)
			.toBeDefined()
		// Should have multiple class names (a, b, c, d)
		expect(result!.code)
			.toMatch(/['"]a b c d['"]/)

		const css = await ctx.getCssCodegenContent()
		expect(css)
			.toContain('color: red')
		expect(css)
			.toContain('display: flex')
		expect(css)
			.toContain('font-size: 16px')
		expect(css)
			.toContain('padding: 10px')
	})

	it('should handle complex CSS values', async () => {
		const code = `const styles = pika({ 
			boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
			background: 'linear-gradient(to right, #ff0000, #00ff00)'
		})`
		const result = await ctx.transform(code, 'Card.tsx')

		expect(result)
			.toBeDefined()
		expect(result!.code)
			.toMatch(/['"]a b['"]/)

		const css = await ctx.getCssCodegenContent()
		expect(css)
			.toContain('box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1)')
		expect(css)
			.toContain('background: linear-gradient(to right, #ff0000, #00ff00)')
	})

	it('should generate preflights in CSS output', async () => {
		await ctx.transform('const s = pika({ color: "red" })', 'test.ts')

		const css = await ctx.getCssCodegenContent()

		// CSS output should include auto-generated comment and preflights
		expect(css)
			.toContain('Auto-generated by @pikacss/integration')
		// Preflights section should exist (even if empty)
		expect(css)
			.toBeDefined()
	})

	it('should track atomic style IDs correctly', async () => {
		const code = `const styles = pika({ color: 'red', display: 'flex' })`
		await ctx.transform(code, 'Button.tsx')

		const usages = ctx.usages.get('Button.tsx')
		expect(usages)
			.toBeDefined()
		expect(usages)
			.toHaveLength(1)

		if (usages) {
			expect(usages[0].atomicStyleIds)
				.toEqual(['a', 'b'])
			expect(usages[0].params)
				.toEqual([{ color: 'red', display: 'flex' }])
		}
	})
})
