import { describe, expect, it } from 'vitest'
import { createCtx } from './ctx'

describe('ctx', () => {
	it('throws before setup and then transforms code into generated class names', async () => {
		const ctx = createCtx({
			cwd: process.cwd(),
			currentPackageName: '@pikacss/integration',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: { prefix: 'it-' },
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: 'pika.gen.ts',
			cssCodegen: 'pika.gen.css',
			autoCreateConfig: true,
		})

		expect(() => ctx.engine)
			.toThrow('Engine is not initialized yet')
		await ctx.setup()

		const transformed = await ctx.transform('const cls = pika({ color: "red" }, "unknown")', 'entry.ts')
		const css = await ctx.getCssCodegenContent()
		const ts = await ctx.getTsCodegenContent()

		expect(ctx.resolvedConfig)
			.toEqual({ prefix: 'it-', plugins: expect.any(Array) })
		expect(transformed?.code)
			.toContain('\'unknown it-a\'')
		expect(ctx.usages.get('entry.ts'))
			.toEqual([
				{ atomicStyleIds: ['unknown', 'it-a'], params: [{ color: 'red' }, 'unknown'] },
			])
		expect(css)
			.toContain('/* Auto-generated by @pikacss/integration */')
		expect(css)
			.toContain('.it-a')
		expect(ts)
			.toContain('const pika: StyleFn')
		expect(ctx.transformFilter.exclude.some(path => path.endsWith('pika.gen.css')))
			.toBe(true)
		expect(ctx.transformFilter.exclude.some(path => path.endsWith('pika.gen.ts')))
			.toBe(true)
	})

	it('returns null ts codegen content when tsCodegen is disabled', async () => {
		const ctx = createCtx({
			cwd: process.cwd(),
			currentPackageName: '@pikacss/integration',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'array',
			tsCodegen: false,
			cssCodegen: 'pika.gen.css',
			autoCreateConfig: true,
		})

		await ctx.setup()

		await expect(ctx.getTsCodegenContent()).resolves.toBeNull()
	})

	it('supports normal array output plus force-string and force-array transform variants', async () => {
		const ctx = createCtx({
			cwd: process.cwd(),
			currentPackageName: '@pikacss/integration',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: { prefix: 'mix-' },
			fnName: 'pika',
			transformedFormat: 'array',
			tsCodegen: false,
			cssCodegen: 'pika.gen.css',
			autoCreateConfig: false,
		})

		await ctx.setup()

		const transformed = await ctx.transform([
			'const normal = pika({ color: "red" })',
			'const asString = pika.str({ backgroundColor: "blue" })',
			'const asArray = pika.arr({ margin: "1rem" })',
		].join('\n'), 'variants.ts')

		expect(transformed?.code)
			.toContain('const normal = [\'mix-a\']')
		expect(transformed?.code)
			.toContain('const asString = \'mix-b\'')
		expect(transformed?.code)
			.toContain('const asArray = [\'mix-c\']')
		expect(ctx.usages.get('variants.ts'))
			.toEqual([
				{ atomicStyleIds: ['mix-a'], params: [{ color: 'red' }] },
				{ atomicStyleIds: ['mix-b'], params: [{ backgroundColor: 'blue' }] },
				{ atomicStyleIds: ['mix-c'], params: [{ margin: '1rem' }] },
			])
	})

	it('returns undefined when a file has no matching style function calls', async () => {
		const ctx = createCtx({
			cwd: process.cwd(),
			currentPackageName: '@pikacss/integration',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: {},
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			cssCodegen: 'pika.gen.css',
			autoCreateConfig: false,
		})

		await ctx.setup()

		await expect(ctx.transform('const untouched = "value"', 'plain.ts')).resolves.toBeUndefined()
		expect(ctx.usages.has('plain.ts'))
			.toBe(false)
	})

	it('supports preview function variants without changing transform routing', async () => {
		const ctx = createCtx({
			cwd: process.cwd(),
			currentPackageName: '@pikacss/integration',
			scan: { include: ['src/**/*.ts'], exclude: [] },
			configOrPath: { prefix: 'pv-' },
			fnName: 'pika',
			transformedFormat: 'string',
			tsCodegen: false,
			cssCodegen: 'pika.gen.css',
			autoCreateConfig: false,
		})

		await ctx.setup()

		const transformed = await ctx.transform([
			'const normal = pikap({ color: "red" })',
			'const asString = pikap.str({ backgroundColor: "blue" })',
			'const asArray = pikap.arr({ margin: "1rem" })',
		].join('\n'), 'preview.ts')

		expect(transformed?.code)
			.toContain('const normal = \'pv-a\'')
		expect(transformed?.code)
			.toContain('const asString = \'pv-b\'')
		expect(transformed?.code)
			.toContain('const asArray = [\'pv-c\']')
	})
})
